[versions]
antlr = "4.13.1"
commons-io = "2.15.1"
commons-lang = "3.12.0"
commons-text = "1.11.0"
discord-ipc = "0.2.2"
docker = "3.2.13"
foojay-resolver-convention = "0.7.0" # Also update manually in settings.gradle.kts
gitversion = "3.0.0"
guava = "32.1.3-jre"
jackson = "2.15.3"
junit = "5.10.0"
junit-jupiter = "5.10.0"
junixsocket = "2.8.3"
konf = "1.1.2"
logback = "1.4.14"
okhttp3 = "4.12.0"
pngtastic = "1.7"
shadow = "8.1.1"
versions = "0.49.0"
zeroAllocationHashing = "0.16"

ide-common = "2021.2" # Lower bound for all IDE versions
ide-pre223 = "2021.2" # Uses Java 11
ide-pre231 = "2022.3.3" # Uses Java 17
ide-post231 = "2023.1.5"

intellij-common = "1.16.1"
intellij-pre223 = "1.16.1"
intellij-pre231 = "1.16.1"
intellij-post231 = "1.16.1"

kotlin-latest = "1.9.22"
kotlin-common = "1.7.0"
kotlin-pre223 = "1.7.0"
kotlin-pre231 = "1.9.22"
kotlin-post231 = "1.9.22"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.3.3"

[libraries]
antlr = { group = "org.antlr", name = "antlr4", version.ref = "antlr" }
antlr-runtime = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
commons-lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
discord-ipc = { group = "com.github.cbyrneee", name = "azn9_KDiscordIPC", version.ref = "discord-ipc" }
docker = { group = "com.github.docker-java", name = "docker-java", version.ref = "docker" }
gradle-shadow = { group = "gradle.plugin.com.github.jengelman.gradle.plugins", name = "shadow", version.ref = "shadow" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml" }
junixsocket-core = { group = "com.kohlschutter.junixsocket", name = "junixsocket-core", version.ref = "junixsocket" }
konf-core = { group = "com.uchuhimo", name = "konf-core", version.ref = "konf" }
konf-yaml = { group = "com.uchuhimo", name = "konf-yaml", version.ref = "konf" }
kotlin-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-compiler-embeddable" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime" }
kotlin-scripting-compiler-embeddable = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-compiler-embeddable" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlinx-serialization" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
pngtastic = { group = "com.github.depsypher", name = "pngtastic", version.ref = "pngtastic" }
zeroAllocationHashing = { group = "net.openhft", name = "zero-allocation-hashing", version.ref = "zeroAllocationHashing" }

ide-common = { group = "com.jetbrains.intellij.idea", name = "ideaIC", version.ref = "ide-common" }
ide-pre223 = { group = "com.jetbrains.intellij.idea", name = "ideaIC", version.ref = "ide-pre223" }
ide-pre231 = { group = "com.jetbrains.intellij.idea", name = "ideaIC", version.ref = "ide-pre231" }
ide-post231 = { group = "com.jetbrains.intellij.idea", name = "ideaIC", version.ref = "ide-post231" }

kotlin-bom-ide = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin-common" }
kotlin-bom-latest = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin-common" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin-common" }
kotlinx-coroutines-bom-ide = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-bom-latest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
docker = { id = "docker" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }
gitversion = { id = "com.palantir.git-version", version.ref = "gitversion" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

kotlin-latest = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-latest" }
kotlin-common = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-common" }
kotlin-pre223 = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-pre223" }
kotlin-pre231 = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-pre231" }
kotlin-post231 = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-post231" }

intellij-common = { id = "org.jetbrains.intellij", version.ref = "intellij-common" }
intellij-pre223 = { id = "org.jetbrains.intellij", version.ref = "intellij-pre223" }
intellij-pre231 = { id = "org.jetbrains.intellij", version.ref = "intellij-pre231" }
intellij-post231 = { id = "org.jetbrains.intellij", version.ref = "intellij-post231" }
